### ISSUE TITLE
Negative density in the last frame when I run aurora_sim

### ISSUE THREAD

**Issue by inwoo-song** [fsciortino/Aurora#56]
Hi Francesco,
Every time I run aurora_sim, I got results of negative density in the last frame.
Even the tutorial shows the same result with the same input. It appears only in the last frame, so I think it's just minor problem but I want to make sure. Could you check this out?

![image002](https://user-images.githubusercontent.com/104437083/165417426-e607924f-a5b5-415e-b451-4ff27520b27c.png)

**Comment by fsciortino** [comment]
Hi @inwoo-song, indeed this issue is known -- but not really understood. I've never dived into this problem because, as you said, it's something that only affects the last time slice -- which can just be ignored. However, it would indeed be nice to clean this up... please let me know if you see a fix. 

More broadly, note that negative densities can happen in the main part of the simulation n some extreme conditions, e.g. with very sharp gradients of diffusion in the pedestal. There is no easy solution for these cases. The algorithm used by Aurora (the Linder finite-volume modification of the Behringer-Lackner method used in STRAHL) is much better at avoiding this issue with respect to the older algorithm, but it still doesn't fundamentally prevent negative densities from occurring. I'm writing this just to give you some context, but this may never be a concern for you unless you're trying such extreme combinations of transport coefficients.

**Comment by odstrcilt** [comment]
The reason is that the influx in the last time step is zero. We should repair it.

**Comment by odstrcilt** [comment]
Here is a fix https://github.com/fsciortino/Aurora/pull/70
